spring:
  cloud:
    config:
      uri: http://192.168.19.73:8888
      name: eureka-service
      label: master
      profile: master
# spring:
#   application:
#     name: eureka
# server:
#    port: 8761          # 指定该Eureka实例的端口
# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false
#     serviceUrl:
#       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#   instance:
#    hostname: localhost         # 指定该Eureka实例的主机名
#    prefer-ip-address: true
